-- Virtual Expert RAG knowledge seed.
-- This SQL file is a durable source copy of the demo knowledge used to seed Qdrant.
-- Import with infra/dev/import-sql.sh, then run server-agent/scripts/seed_qdrant.py to populate vectors.

CREATE TABLE IF NOT EXISTS "public"."rag_seed_document" (
  "id" varchar(128) NOT NULL,
  "collection_name" varchar(64) NOT NULL,
  "doc_id" varchar(128) NOT NULL,
  "chunk_id" varchar(64) NOT NULL DEFAULT 'main',
  "title" varchar(240) NOT NULL,
  "content" text NOT NULL,
  "summary" text NOT NULL,
  "tags" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "risk_level" varchar(32) NOT NULL DEFAULT 'medium',
  "object_types" jsonb NOT NULL DEFAULT '["pipeline","pipe_segment","equipment","sensor"]'::jsonb,
  "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "pk_rag_seed_document" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_rag_seed_document_collection_doc_chunk"
  ON "public"."rag_seed_document" ("collection_name", "doc_id", "chunk_id");

INSERT INTO "public"."rag_seed_document"
("id", "collection_name", "doc_id", "chunk_id", "title", "content", "summary", "tags", "risk_level", "metadata")
VALUES
('rag_domain_pressure_sop_main', 'domain_knowledge', 'domain_pressure_sop', 'main', '管道压力异常处置 SOP',
 $$当管段压力出现连续波动时，应先校验压力传感器状态，再比对上下游流量和阀门开度。$$,
 $$压力异常应先校验传感器，再联动查看流量、阀门和上下游变化。$$,
 '["pressure","sop","pipeline"]'::jsonb, 'medium', '{"seeded_demo":true,"seed_index":0}'::jsonb),
('rag_domain_cp_voltage_rule_main', 'domain_knowledge', 'domain_cp_voltage_rule', 'main', '阴保电位异常判断规则',
 $$阴保电位短时漂移需要结合土壤湿度、测试桩状态和近期检修记录判断，避免误判为腐蚀风险。$$,
 $$阴保电位异常需要结合环境、测试桩和检修记录综合判断。$$,
 '["cp_voltage","corrosion","rule"]'::jsonb, 'medium', '{"seeded_demo":true,"seed_index":1}'::jsonb),
('rag_domain_pump_flow_drop_main', 'domain_knowledge', 'domain_pump_flow_drop', 'main', '泵站流量突降排查步骤',
 $$泵站流量突降时，应检查泵组运行状态、入口压力、过滤器压差和下游阀室状态。$$,
 $$流量突降优先排查泵组、入口压力、过滤器和下游阀室。$$,
 '["flow","pump","inspection"]'::jsonb, 'high', '{"seeded_demo":true,"seed_index":2}'::jsonb),
('rag_domain_valve_temperature_main', 'domain_knowledge', 'domain_valve_temperature', 'main', '阀室温度异常应急建议',
 $$阀室温度持续升高时，应核查通风、伴热、电气柜负载和可燃气体报警状态。$$,
 $$阀室温度异常需要联动检查通风、伴热、电气柜和气体报警。$$,
 '["temperature","valve","emergency"]'::jsonb, 'high', '{"seeded_demo":true,"seed_index":3}'::jsonb),
('rag_domain_sensor_drift_main', 'domain_knowledge', 'domain_sensor_drift', 'main', '传感器离线和漂移判断规则',
 $$传感器离线或漂移应先确认通信链路、电源、采样频率和邻近传感器趋势一致性。$$,
 $$传感器异常先判断通信、电源、采样频率和邻近趋势一致性。$$,
 '["sensor","offline","drift"]'::jsonb, 'low', '{"seeded_demo":true,"seed_index":4}'::jsonb),
('rag_domain_pressure_drop_isolation_main', 'domain_knowledge', 'domain_pressure_drop_isolation', 'main', '管段压力突降隔离研判要点',
 $$管段压力突降应先确认上下游压力是否同步变化，再核查阀门误关、泵站启停、泄漏告警和近期施工记录。若压力突降伴随流量异常增大，应优先按泄漏风险升级处置。$$,
 $$压力突降需要联动上下游压力、阀门、泵站、泄漏告警和施工记录判断。$$,
 '["pressure","isolation","leakage","valve"]'::jsonb, 'high', '{"seeded_demo":true,"seed_index":5}'::jsonb),
('rag_domain_flow_pressure_correlation_main', 'domain_knowledge', 'domain_flow_pressure_correlation', 'main', '流量与压力联动异常判断',
 $$流量下降且压力升高通常提示下游阻塞或阀门开度不足；流量上升且压力下降需要关注泄漏、旁通开启或计量偏差；单指标异常时应优先复核传感器状态。$$,
 $$流量和压力的组合变化可区分阻塞、泄漏、旁通和传感器偏差。$$,
 '["flow","pressure","correlation","diagnosis"]'::jsonb, 'medium', '{"seeded_demo":true,"seed_index":6}'::jsonb),
('rag_domain_third_party_construction_main', 'domain_knowledge', 'domain_third_party_construction', 'main', '第三方施工影响排查清单',
 $$发现第三方施工风险时，应核对施工许可、管线定位、现场监护、告警时间线和最近巡检照片。对高后果区管段，应要求现场复核并保持调度联络。$$,
 $$第三方施工风险需要核对许可、定位、监护、告警和巡检照片。$$,
 '["construction","inspection","risk","pipeline"]'::jsonb, 'high', '{"seeded_demo":true,"seed_index":7}'::jsonb),
('rag_domain_valve_remote_operation_main', 'domain_knowledge', 'domain_valve_remote_operation', 'main', '远程阀门操作前置核查',
 $$远程开闭阀前应确认阀门状态反馈、上下游压力差、现场作业票、联锁条件和通信质量。状态反馈不一致时，不应仅凭单一遥测值执行动作。$$,
 $$远程阀门动作前要确认状态反馈、压差、作业票、联锁和通信质量。$$,
 '["valve","remote_operation","safety","checklist"]'::jsonb, 'high', '{"seeded_demo":true,"seed_index":8}'::jsonb),
('rag_domain_report_export_policy_main', 'domain_knowledge', 'domain_report_export_policy', 'main', '虚拟专家报告导出内容规范',
 $$导出研判报告应包含用户问题、风险判断、关键证据、处置建议和待补充信息。面向领导汇报时应减少过程细节，面向现场处置时应保留证据和操作顺序。$$,
 $$导出报告应按受众调整证据、过程和处置动作的详略。$$,
 '["export","report","evidence","audience"]'::jsonb, 'low', '{"seeded_demo":true,"seed_index":9}'::jsonb),
('rag_case_pressure_001_main', 'case_knowledge', 'case_pressure_001', 'main', '压力波动相似案例',
 $$某输油管段压力在 40 分钟内反复波动，最终确认为压力传感器接线松动叠加阀门开度调整。$$,
 $$压力波动案例：传感器接线松动与阀门调整共同导致异常。$$,
 '["pressure","sensor","valve"]'::jsonb, 'medium', '{"seeded_demo":true,"seed_index":0}'::jsonb),
('rag_case_cp_001_main', 'case_knowledge', 'case_cp_001', 'main', '阴保电位波动相似案例',
 $$雨后阴保电位出现短时波动，经复核为测试桩接触不良，未发现腐蚀扩大迹象。$$,
 $$阴保电位波动案例：雨后测试桩接触不良造成误报。$$,
 '["cp_voltage","rain","false_positive"]'::jsonb, 'low', '{"seeded_demo":true,"seed_index":1}'::jsonb),
('rag_case_flow_001_main', 'case_knowledge', 'case_flow_001', 'main', '流量突降相似案例',
 $$东区泵站流量突降，工具趋势显示入口压力同步下降，现场发现过滤器堵塞。$$,
 $$流量突降案例：入口压力下降与过滤器堵塞相关。$$,
 '["flow","pump","filter"]'::jsonb, 'high', '{"seeded_demo":true,"seed_index":2}'::jsonb),
('rag_case_temperature_001_main', 'case_knowledge', 'case_temperature_001', 'main', '阀室温度异常相似案例',
 $$阀室温度持续升高，检查发现通风设备停转，恢复通风后温度回落。$$,
 $$温度异常案例：通风设备停转导致阀室升温。$$,
 '["temperature","valve","ventilation"]'::jsonb, 'medium', '{"seeded_demo":true,"seed_index":3}'::jsonb),
('rag_case_device_offline_001_main', 'case_knowledge', 'case_device_offline_001', 'main', '设备离线误报案例',
 $$多个传感器同一时刻离线，排查后确认为通信网关重启，不属于设备本体故障。$$,
 $$设备离线案例：通信网关重启造成批量离线误报。$$,
 '["sensor","offline","gateway"]'::jsonb, 'low', '{"seeded_demo":true,"seed_index":4}'::jsonb),
('rag_case_pressure_drop_002_main', 'case_knowledge', 'case_pressure_drop_002', 'main', '压力突降与阀门误关案例',
 $$西线 7 号管段压力在 15 分钟内下降 18%，流量同步下降。现场复核发现下游阀室检修后阀门未完全复位，恢复开度后压力回稳。$$,
 $$压力和流量同步下降案例：下游阀门未复位造成输送受限。$$,
 '["pressure","flow","valve","maintenance"]'::jsonb, 'medium', '{"seeded_demo":true,"seed_index":5}'::jsonb),
('rag_case_leakage_003_main', 'case_knowledge', 'case_leakage_003', 'main', '压力下降伴流量升高泄漏案例',
 $$城区支线夜间压力下降且瞬时流量升高，巡检发现第三方施工点附近土壤湿润并有异味，按泄漏预案隔离后确认外力损伤。$$,
 $$压力下降伴流量升高案例：第三方施工导致泄漏风险升级。$$,
 '["leakage","construction","pressure","flow"]'::jsonb, 'critical', '{"seeded_demo":true,"seed_index":6}'::jsonb),
('rag_case_valve_feedback_001_main', 'case_knowledge', 'case_valve_feedback_001', 'main', '阀门遥测反馈不一致案例',
 $$调度准备远程关阀时，阀位反馈与现场视频不一致。暂停操作后发现阀位传感器卡滞，避免了一次误操作。$$,
 $$阀门反馈不一致案例：暂停远程动作并现场核验避免误操作。$$,
 '["valve","remote_operation","sensor","safety"]'::jsonb, 'high', '{"seeded_demo":true,"seed_index":7}'::jsonb),
('rag_case_report_export_001_main', 'case_knowledge', 'case_report_export_001', 'main', '现场处置报告导出案例',
 $$一次压力异常研判结束后，值班员导出 PDF 给现场人员。报告保留了压力趋势、阀门检查顺序和待补充信息，现场按清单完成复核。$$,
 $$现场处置导出案例：PDF 保留证据和操作顺序，便于现场执行。$$,
 '["export","pdf","field_response","pressure"]'::jsonb, 'low', '{"seeded_demo":true,"seed_index":8}'::jsonb),
('rag_case_alarm_closure_001_main', 'case_knowledge', 'case_alarm_closure_001', 'main', '告警闭环延迟案例',
 $$某高压告警已恢复正常但工单未闭环，复盘发现班组交接遗漏。后续要求报告中列出未闭环任务和责任人。$$,
 $$告警闭环案例：恢复正常不等于流程闭环，需要同步任务状态。$$,
 '["alarm","task","handover","report"]'::jsonb, 'medium', '{"seeded_demo":true,"seed_index":9}'::jsonb)
ON CONFLICT ("id") DO UPDATE SET
  "collection_name" = EXCLUDED."collection_name",
  "doc_id" = EXCLUDED."doc_id",
  "chunk_id" = EXCLUDED."chunk_id",
  "title" = EXCLUDED."title",
  "content" = EXCLUDED."content",
  "summary" = EXCLUDED."summary",
  "tags" = EXCLUDED."tags",
  "risk_level" = EXCLUDED."risk_level",
  "metadata" = EXCLUDED."metadata",
  "updated_at" = now();
